config:
  - key: config/services/secrets/protocols/http/host
    value: active.secrets

  - key: config/services/secrets/protocols/http/port
    value: 8200

  - key: config/services/secrets/metrics/statsd/rules
    file: secrets_statsd_rules.txt
